url : https://arnaud-engineer.github.io/arnaud-cool-blog

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "authors"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-feed
title: arnaud.cool blog
description: a blog about cool stuffs
author: arnaud.cool
